version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: arekczarnik/docker-circleci-haskell
      - image: richnorth/disque:latest
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "haskell-disque.cabal" }}
      - run: stack build --fast
      - run: stack test --no-terminal --coverage
      - run: stack exec -- shc --repo-token=$COVERALLS_REPO_TOKEN haskell-disque haskell-disque-test
      - save_cache:
          paths:
            - ~/.stack
            - ~/uthenga/.stack-work
          key: cache-{{ checksum "haskell-disque.cabal" }}